DROP TABLE IF EXISTS "freshwaterFish";
CREATE TABLE "freshwaterFish" ("name" TEXT DEFAULT (null) ,"legalLength" TEXT DEFAULT (null) ,"maxCatch" TEXT DEFAULT (null) ,"recommendedTackle" TEXT DEFAULT (null) );
INSERT INTO "freshwaterFish" VALUES('Bass, Black','some length','none!','Old Rod');
INSERT INTO "freshwaterFish" VALUES('Tilapia','I''m filling','just kidding','new rod');
INSERT INTO "freshwaterFish" VALUES('Bass, White','the table','filling a table','hot rod');
INSERT INTO "freshwaterFish" VALUES('Perch, Yellow','with good stuff','I don''t know','not that rod');
INSERT INTO "freshwaterFish" VALUES('Eulachon','this','ewww','big rod');
INSERT INTO "freshwaterFish" VALUES('Bullhead','is to test','you can''t catch this','asian rod');
INSERT INTO "freshwaterFish" VALUES('Catfish','that it will work','we''re still going','cold rod');
INSERT INTO "freshwaterFish" VALUES('Corvina','GO','eww','my rod');
INSERT INTO "freshwaterFish" VALUES('Whitefish, Mountain','stop it','we''re still going','still going');
INSERT INTO "freshwaterFish" VALUES('Pike, Northern','now stop it','almost done','can''t stop me');
INSERT INTO "freshwaterFish" VALUES('Lamprey','still going','still trying','woop woop');
INSERT INTO "freshwaterFish" VALUES('Shad, American','I''m still going at it','and here we are','here we go');
INSERT INTO "freshwaterFish" VALUES('Bass, Striped','whyyy!!','done','done');
DROP TABLE IF EXISTS "saltwaterFish";
CREATE TABLE "saltwaterFish" ("name" TEXT,"legalLength" TEXT,"maxCatch" TEXT,"recommendedTackle" TEXT);
INSERT INTO "saltwaterFish" VALUES('Pacific Halibut','some length','One fish','this is the last column');
INSERT INTO "saltwaterFish" VALUES('California Halibut','22 Inches','Two fish','where we put the fricking takle');
INSERT INTO "saltwaterFish" VALUES('Sturgeon','Between 40 and 60 inches Fork Length','One Fish','it takes so long');
INSERT INTO "saltwaterFish" VALUES('Sablefish','this long','red fish','but my databaseis almost ready to test');
INSERT INTO "saltwaterFish" VALUES('Salmon','that''s too long','blue fish','here we go');
INSERT INTO "saltwaterFish" VALUES('Sole','whoa there','my fish','this takes forever');
INSERT INTO "saltwaterFish" VALUES('Swordfish','you''re cute','our fish','I miss my girlfriend ):');
INSERT INTO "saltwaterFish" VALUES('Tuna, Albacore','hey you are','has rabies','she''s dancing on that big boat');
INSERT INTO "saltwaterFish" VALUES('Tuna, Bluefin','coming on a little','my fish','eminem is pretty good though');
INSERT INTO "saltwaterFish" VALUES('Tuna, Yellowfin','strong there','has babies!','here we go again');
INSERT INTO "saltwaterFish" VALUES('Barracuda','let''s end this','and here we go','third to last');
INSERT INTO "saltwaterFish" VALUES('Rockfish','now','almost here','second to last');
INSERT INTO "saltwaterFish" VALUES('Mackeral','done','done with it','and done');
